# Generated by Django 4.2.21 on 2025-08-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('business_area', models.CharField(max_length=256, verbose_name='Направление деятельности')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('url', models.URLField(max_length=256, verbose_name='Адрес проекта')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('screenshot', models.ImageField(upload_to='screenshots', verbose_name='Скриншот')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=256, verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'инструмент',
                'verbose_name_plural': 'Инструмент',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_job', models.DateField(verbose_name='Начало работы')),
                ('end_job', models.DateField(verbose_name='Окончание работы')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='resume.organisation', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'место работы',
                'verbose_name_plural': 'Места работы',
                'ordering': ('-end_job',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=256, verbose_name='Образовательная программа')),
                ('qualification', models.CharField(max_length=256, verbose_name='Квалификация')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='resume.institute', verbose_name='Образовательное учреждение')),
            ],
            options={
                'verbose_name': 'образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
    ]
